### PR TITLE
Basic functions

### PR DESCRIPTION
**Pull request by Zankoku-Okuno**
simple implementations for insert, insertWith, null, empty

### CODE REVIEW

**Comment by andrewthad** [comment]
This looks mostly fine. It has merge conflicts, and some documentation on `insertWith` would be nice since I never can remember whether it's `f old new` or `f new old` that gets called.

**Comment by Zankoku-Okuno** [comment]
actually, when I run the tests, it gives up on my new test case sometimes; should I worry about that?

**Comment by andrewthad** [comment]
Yes, that is not a good sign. The problem is that your precondition throws out a lot of possible inputs. You are requiring that a randomly chosen map happened to have `k` in it. One solution would be to push something on to the list before building the map: `Map.fromList ((k,4625364) : alist)`.

**Comment by andrewthad** [comment]
Merged.

**Pull request merged**
